### ISSUE TITLE
api.util.Mathematics.makePrimeGreater, makePrimeLesser fail for certain inputs

### ISSUE THREAD

**Issue by geoff-m** [Dyndrilliac/java-custom-api#1]
Calling makePrimeGreater with an even number less than 2 will return 3 instead of the expected 2.

Calling makePrimeGreater or makePrimeLesser with a prime number will return that number instead of the expected "first prime number [greater/less] than a given integer".

Calling makePrimeLesser with a number less than 2 will take a long time to execute and then return the largest prime less than 2^63-1.

Calling makePrimeGreater with a number greater than the largest prime less than 2^63-1 will take a long time to execute and then return 2.

**Comment by Dyndrilliac** [comment]
Thanks for the input! I really appreciate it. I've fixed the issues. Calling makePrimeGreater with an even number less than two will now return the expected value. Calling makePrimeLesser with a number less than two will throw an IllegalArgumentException (as there are no primes less than two). Calling makePrimeGreater with a number greater than the largest prime less than `2^63-1` will likewise throw an IllegalArgumentException. Tested using [this Gist](https://gist.github.com/Dyndrilliac/487fc06ddc47ab55968180358c60691b).

The second problem you identified is the intended behavior; I have updated the comments to reflect that. I may consider adding separate methods to handle those cases. The intended use-cases for those methods were selecting the proper integer to use in modulo division regarding the upper-bounds for hash tables based on powers of two, since prime integers produce less collisions when used as the capacity of a hash table. You can see the intended usage in [api.util.datastructures.SeparateChainingSymbolTable.java](https://github.com/Dyndrilliac/java-custom-api/blob/master/api/util/datastructures/SeparateChainingSymbolTable.java) which was heavily based on the [SeparateChainingHashST](http://algs4.cs.princeton.edu/34hash/SeparateChainingHashST.java.html) class found in *Algorithms, 4th Edition* by Robert Sedgewick and Kevin Wayne.

Commit: 4c40d653fcdf63194444b6eecd33dfa02b2df797
